export { calculateTotal } from './calculateTotal'
export { coreRandom } from './coreRandom'
export { coreSpreadRolls } from './coreSpreadRolls'
export { generateKey } from './generateKey'
export { generateNumericalFaces } from './generateNumericalFaces'
export { normalizeArgument } from './normalizeArgument'
export { rollResultFromDicePools } from './rollResultFromDicePools'
