#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

(yarn test || exit 1) && (yarn build || exit 1) && yarn docs

if [ ! -z "$(git status --porcelain ./docs  )" ]; then
  git add ./docs
  git commit -m "Updating Docs..." --no-verify

  echo "Generated docs 👍"
fi
