#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn test && yarn build && typedoc --options ./typedoc.json

if [ ! -z "$(git status --porcelain ./docs  )" ]; then
  git add ./docs
  git commit -m "Updating Docs..." --no-verify
  echo "Generated docs 👍"
fi
